### PR TITLE
Update for owncloud version seven

### PR DESCRIPTION
**Pull request by Dude4Linux**
These changes dynamically update the config.php file, adding the list of 'trusted domains' (actually host headers used to access the ownCloud server).  The changes work with both version 6.x and the newly released 7.0 version of ownCloud.  The updates rely on the separate pull request create-ssl-cert-with-subject-alternative-names-SAN.

### CODE REVIEW

**Comment by alonswartz** [comment]
Sorry for the really late response. 

Could you point me to the "separate pull request create-ssl-cert-with-subject-alternative-names-SAN" you mentioned?

**Comment by Dude4Linux** [comment]
That was the pull request that I withdrew.  I found that while the ownCloud client would accept the SAN certificate that was generated, neither Chrome nor Safari was satisfied.  I managed to figure out how to modify the certificates so that both browsers and the ownCloud client were happy.  In the meantime, I had purchased a copy of Ivan Ristić's book, Bulletproof SSL and TLS.  I just haven't had time to rewrite the program with the new information.  In a previous comment, I had asked you for a deadline for the next release.  I'm currently working on a project for a new website for our church and it has been taking all my time lately.  If I knew when you were planning the release, I might be able to prioritize this.

Also version 8 of ownCloud has been released and there are some more changes that should be included to update the documentation.

**Comment by alonswartz** [comment]
We are aiming for TurnKey 14 based on Jessie within the next month or two. @JedMeister is coordinating the effort, so I'm looping him.

**Comment by alonswartz** [comment]
closing - partially included in #6

**Pull request closed without merging**
